steps:
  - name: 'gradle:7.5.0-jdk17'
    args:
      - shadowJar
    entrypoint: gradle
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/pokebuild/pokebuild-buck
      - '--build-arg'
      - _DB_PATH=$_DB_PATH
      - '--build-arg'
      - _DB_USER=$_DB_USER
      - '--build-arg'
      - _DB_PASS=$_DB_PASS
      - '--build-arg'
      - _AUTH0_ISSUER=$_AUTH0_ISSUER
      - '--build-arg'
      - _AUTH0_AUDIENCE=$_AUTH0_AUDIENCE
      - '--build-arg'
      - _AUTH0_SECRET=$_AUTH0_SECRET
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/pokebuild/pokebuild-buck
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - pokemonbuildback
      - '--image'
      - gcr.io/pokebuild/pokebuild-buck
      - '--region'
      - asia-northeast1
    entrypoint: gcloud
images:
  - gcr.io/pokebuild/pokebuild-buck